<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
      integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
      defer
    ></script>

    <title>{% block title %} Default Title {% endblock %}</title>
    {% block head %}
    <!-- Default Head Content -->
    {% endblock %}
  </head>

  <body>
    {% include 'partials/_navbar.html' %} {% include 'partials/_flashes.html' %}
    {% block body %}
    <!-- Default Body Content -->
    {% endblock %} {% block scripts %}
    <!-- Default Scripts Content -->
    {% endblock %}

    <script>
      async function fetchWithRetry(url, retries = 3, delay = 2000) {
        for (let i = 0; i < retries; i++) {
          try {
            const res = await fetch(url);
            if (!res.ok) throw new Error("Failed");
            return await res.json();
          } catch (err) {
            if (i < retries - 1) {
              await new Promise((r) => setTimeout(r, delay));
            } else {
              console.error("Server didn't wake up in time:", err);
            }
          }
        }
      }

      document.addEventListener("DOMContentLoaded", () => {
        fetchWithRetry("/ping", 3, 2000)
          .then((data) => console.log("Server ready:", data))
          .catch((err) => console.error("Error:", err));
      });
    </script>
  </body>
</html>
